=begin
#voyager-server

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v0
Contact: hello@appscode.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

# Common files
require 'kubernetes/api_client'
require 'kubernetes/api_error'
require 'kubernetes/version'
require 'kubernetes/configuration'

# Models
require 'kubernetes/models/v1beta1_acme_certificate_details'
require 'kubernetes/models/v1beta1_auth_option'
require 'kubernetes/models/v1beta1_basic_auth'
require 'kubernetes/models/v1beta1_certificate'
require 'kubernetes/models/v1beta1_certificate_condition'
require 'kubernetes/models/v1beta1_certificate_details'
require 'kubernetes/models/v1beta1_certificate_list'
require 'kubernetes/models/v1beta1_certificate_spec'
require 'kubernetes/models/v1beta1_certificate_status'
require 'kubernetes/models/v1beta1_certificate_storage'
require 'kubernetes/models/v1beta1_challenge_provider'
require 'kubernetes/models/v1beta1_dns_challenge_provider'
require 'kubernetes/models/v1beta1_frontend_rule'
require 'kubernetes/models/v1beta1_http_challenge_provider'
require 'kubernetes/models/v1beta1_http_ingress_backend'
require 'kubernetes/models/v1beta1_http_ingress_path'
require 'kubernetes/models/v1beta1_http_ingress_rule_value'
require 'kubernetes/models/v1beta1_ingress'
require 'kubernetes/models/v1beta1_ingress_backend'
require 'kubernetes/models/v1beta1_ingress_list'
require 'kubernetes/models/v1beta1_ingress_rule'
require 'kubernetes/models/v1beta1_ingress_spec'
require 'kubernetes/models/v1beta1_ingress_status'
require 'kubernetes/models/v1beta1_ingress_tls'
require 'kubernetes/models/v1beta1_local_typed_reference'
require 'kubernetes/models/v1beta1_tcp_ingress_rule_value'
require 'kubernetes/models/v1beta1_tls_auth'
require 'kubernetes/models/v1beta1_vault_store'

# APIs
require 'kubernetes/api/apis_api'
require 'kubernetes/api/voyager_appscode_com_api'
require 'kubernetes/api/voyager_appscode_com_v1beta1_api'

module Kubernetes
  class << self
    # Customize default settings for the SDK using block.
    #   Kubernetes.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
